export const CREATE_COMPOUND = "CREATE_COMPOUND";
export const RETRIEVE_COMPOUNDS = "RETRIEVE_COMPOUNDS";
export const UPDATE_COMPOUND = "UPDATE_COMPOUND";
export const DELETE_COMPOUND = "DELETE_COMPOUND";
export const DELETE_ALL_COMPOUNDS = "DELETE_ALL_COMPOUNDS";
